[versions]
agp = "8.6.1"
core = "1.13.1"
junit = "4.13.2"
junitExt = "1.2.1"
espresso = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.6.1"         # downgraded for SDK 35
constraintlayout = "2.2.1"
firebaseAuth = "24.0.1"
playServicesAuth = "21.4.0"
firebaseDatabase = "22.0.1"
firebaseFirestore = "26.0.2"

[libraries]
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
